[build]
  publish = "site"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/research"
  to = "/research/index.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/app/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about/index.html"
  status = 200

[[redirects]]
  from = "/support"
  to = "/support/index.html"
  status = 200

[[redirects]]
  from = "/privacypolicy"
  to = "/privacypolicy/index.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/legal/privacy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/legal/terms.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
