import SwiftUI

// Body Weather, the Vida Differential, and the Appointment Concierge: the
// website's Vida+ AI tools, generated by Claude from a summary of the member's
// own check-ins, only after she agrees to send it.

/// Opens one of the tools. Placed where each belongs: Body Weather on Today,
/// the Differential on Patterns, the Concierge in Doctor Prep.
struct InsightLaunchCard: View {
    @Environment(VidaStore.self) private var store
    let feature: InsightFeature
    @State private var isPresented = false

    var body: some View {
        Button { isPresented = true } label: {
            HStack(spacing: 14) {
                Image(systemName: feature.symbol)
                    .font(.system(size: 18, weight: .light))
                    .foregroundStyle(Vida.moss)
                    .frame(width: 44, height: 44)
                    .background(Vida.sage.opacity(0.18), in: Circle())
                    .accessibilityHidden(true)
                VStack(alignment: .leading, spacing: 3) {
                    HStack(spacing: 8) {
                        Text(feature.title)
                            .font(Vida.serif(19))
                            .foregroundStyle(Vida.forest)
                        Text("VIDA+")
                            .font(Vida.sans(9, weight: .bold))
                            .tracking(1)
                            .foregroundStyle(Vida.cream)
                            .padding(.horizontal, 7)
                            .padding(.vertical, 3)
                            .background(Vida.moss, in: Capsule())
                    }
                    Text(feature.tagline)
                        .font(Vida.sans(13))
                        .foregroundStyle(Vida.inkSoft)
                        .multilineTextAlignment(.leading)
                        .fixedSize(horizontal: false, vertical: true)
                }
                Spacer(minLength: 0)
                Image(systemName: "chevron.right")
                    .font(.system(size: 12, weight: .semibold))
                    .foregroundStyle(Vida.taupe)
                    .accessibilityHidden(true)
            }
            .paperCard(padding: 18)
        }
        .buttonStyle(PressableStyle())
        .accessibilityElement(children: .combine)
        .accessibilityLabel("\(feature.title), Vida Plus. \(feature.tagline)")
        .accessibilityAddTraits(.isButton)
        .sheet(isPresented: $isPresented) {
            VidaPlusInsightSheet(feature: feature)
                .presentationDetents([.large])
        }
    }
}

struct VidaPlusInsightSheet: View {
    @Environment(VidaStore.self) private var store
    @Environment(AuthManager.self) private var auth
    @Environment(\.dismiss) private var dismiss
    @AppStorage(ClaudeInsightsDisclosure.acceptedKey) private var consented = false

    let feature: InsightFeature

    @State private var result: InsightResult?
    @State private var generatedAt: Date?
    @State private var notice: String?
    @State private var failure: String?
    @State private var isGenerating = false
    @State private var showConsent = false
    @State private var showPaywall = false
    @State private var visitReason = ""
    @State private var conditionName = ""

    private var memberDays: Int { InsightRequest.days(from: store.logs).count }
    private var hasEnoughDays: Bool { memberDays >= feature.minimumDays }

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 22) {
                    header

                    if !store.isPlus {
                        plusGate
                    } else if !hasEnoughDays {
                        daysNeeded
                    } else {
                        if feature == .concierge { conciergeInputs }
                        generateButton
                        if let failure { message(failure, urgent: true) }
                        if let notice { message(notice, urgent: false) }
                        if let result { resultView(result) }
                    }

                    Text("Vida is for education and personal tracking. It does not diagnose conditions or replace urgent or professional care. If something feels urgent, contact a clinician or emergency services.")
                        .font(Vida.sans(12))
                        .foregroundStyle(Vida.taupe)
                        .lineSpacing(4)
                        .fixedSize(horizontal: false, vertical: true)
                }
                .padding(24)
                .readableColumn()
            }
            .scrollDismissesKeyboard(.interactively)
            .vidaBackground()
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Done") { dismiss() }
                        .foregroundStyle(Vida.moss)
                }
            }
        }
        .onAppear(perform: loadSaved)
        .alert(ClaudeInsightsDisclosure.title, isPresented: $showConsent) {
            Button("Send to Anthropic") {
                consented = true
                Task { await generate() }
            }
            Button("Not now", role: .cancel) { }
        } message: {
            Text(ClaudeInsightsDisclosure.message)
        }
        .sheet(isPresented: $showPaywall) { PaywallView() }
    }

    // MARK: Sections

    private var header: some View {
        VStack(alignment: .leading, spacing: 8) {
            Eyebrow(text: "Vida+", color: Vida.moss)
            Text(feature.title)
                .font(Vida.serif(30))
                .foregroundStyle(Vida.forest)
            Text(feature.tagline + ".")
                .font(Vida.sans(15))
                .foregroundStyle(Vida.inkSoft)
                .lineSpacing(4)
                .fixedSize(horizontal: false, vertical: true)
        }
    }

    private var plusGate: some View {
        VStack(alignment: .leading, spacing: 14) {
            Text("\(feature.title) is part of Vida+.")
                .font(Vida.sans(15, weight: .semibold))
                .foregroundStyle(Vida.forest)
            Button { showPaywall = true } label: {
                Text("Explore Vida+")
                    .font(Vida.sans(15, weight: .semibold))
                    .foregroundStyle(Vida.onForest)
                    .frame(maxWidth: .infinity, minHeight: 50)
                    .background(Vida.forest, in: Capsule())
            }
            .buttonStyle(PressableStyle())
        }
        .paperCard(padding: 18)
    }

    private var daysNeeded: some View {
        message("This needs at least \(feature.minimumDays) days of your own check-ins, and you have \(memberDays) so far. Keep checking in and it will be ready soon.", urgent: false)
    }

    private var conciergeInputs: some View {
        VStack(alignment: .leading, spacing: 14) {
            VStack(alignment: .leading, spacing: 7) {
                Text("What's the visit for?")
                    .font(Vida.sans(12, weight: .semibold))
                    .foregroundStyle(Vida.forest)
                TextField("For example, ongoing fatigue and headaches", text: $visitReason, axis: .vertical)
                    .lineLimit(2...4)
                    .padding(.horizontal, 16)
                    .padding(.vertical, 14)
                    .background(Vida.paper, in: RoundedRectangle(cornerRadius: 14, style: .continuous))
                    .overlay { RoundedRectangle(cornerRadius: 14, style: .continuous).strokeBorder(Vida.hairline, lineWidth: 0.9) }
            }
            VStack(alignment: .leading, spacing: 7) {
                Text("Related condition (optional)")
                    .font(Vida.sans(12, weight: .semibold))
                    .foregroundStyle(Vida.forest)
                TextField("For example, endometriosis", text: $conditionName)
                    .padding(.horizontal, 16)
                    .padding(.vertical, 14)
                    .background(Vida.paper, in: RoundedRectangle(cornerRadius: 14, style: .continuous))
                    .overlay { RoundedRectangle(cornerRadius: 14, style: .continuous).strokeBorder(Vida.hairline, lineWidth: 0.9) }
            }
            Text("What you type here is sent with your check-in summary.")
                .font(Vida.sans(12))
                .foregroundStyle(Vida.inkSoft)
        }
    }

    private var generateButton: some View {
        VStack(alignment: .leading, spacing: 8) {
            Button(action: requestGeneration) {
                HStack(spacing: 9) {
                    if isGenerating { ProgressView().tint(Vida.onForest) }
                    Text(isGenerating ? "Working on it" : buttonTitle)
                }
                .font(Vida.sans(16, weight: .semibold))
                .foregroundStyle(Vida.onForest)
                .frame(maxWidth: .infinity, minHeight: 52)
                .background(Vida.forest, in: Capsule())
            }
            .buttonStyle(PressableStyle())
            .disabled(isGenerating)

            if let generatedAt, result != nil {
                Text("Made \(generatedAt.formatted(date: .abbreviated, time: .shortened)) from \(memberDays) days of check-ins.")
                    .font(Vida.sans(12))
                    .foregroundStyle(Vida.taupe)
            } else if isGenerating {
                Text("This can take up to a minute.")
                    .font(Vida.sans(12))
                    .foregroundStyle(Vida.taupe)
            }
        }
    }

    private var buttonTitle: String {
        if result != nil { return "Make a fresh one" }
        switch feature {
        case .bodyWeather: return "Make my forecast"
        case .differential: return "Map my patterns"
        case .concierge: return "Prepare my visit"
        }
    }

    private func message(_ text: String, urgent: Bool) -> some View {
        Text(text)
            .font(Vida.sans(14))
            .foregroundStyle(urgent ? Vida.clay : Vida.forest)
            .lineSpacing(4)
            .fixedSize(horizontal: false, vertical: true)
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(16)
            .background(Vida.sage.opacity(0.16), in: RoundedRectangle(cornerRadius: 16, style: .continuous))
    }

    @ViewBuilder
    private func resultView(_ result: InsightResult) -> some View {
        switch result {
        case .bodyWeather(let value): BodyWeatherResultView(result: value)
        case .differential(let value): DifferentialResultView(result: value)
        case .concierge(let value): ConciergeResultView(result: value)
        }
    }

    // MARK: Actions

    private func loadSaved() {
        guard let userID = auth.user?.id, let saved = VidaPlusInsightsService.load(feature, userID: userID) else { return }
        result = saved.0
        generatedAt = saved.1
    }

    private func requestGeneration() {
        if consented {
            Task { await generate() }
        } else {
            showConsent = true
        }
    }

    private func generate() async {
        isGenerating = true
        failure = nil
        notice = nil
        defer { isGenerating = false }

        let request = InsightRequest(
            feature: feature,
            today: InsightRequest.dayString(.now, calendar: .current),
            checkIns: InsightRequest.days(from: store.logs),
            context: InsightContext(
                focusAreas: store.profile.focusSignals.map(\.title),
                conditions: store.profile.conditions.map(\.name),
                tracksCycle: store.profile.tracksCycle,
                visitReason: feature == .concierge ? visitReason : "",
                conditionName: feature == .concierge ? conditionName : ""
            )
        )

        switch await VidaPlusInsightsService.generate(request) {
        case .ready(let value, let date):
            result = value
            generatedAt = date
            if let userID = auth.user?.id {
                VidaPlusInsightsService.save(value, generatedAt: date, userID: userID)
            }
        case .notice(let text):
            notice = text
        case .needsPlus:
            showPaywall = true
        case .failed(let text):
            failure = text
        }
    }
}

// MARK: - Result layouts

private struct InsightSection<Content: View>: View {
    let title: String
    @ViewBuilder let content: Content

    var body: some View {
        VStack(alignment: .leading, spacing: 10) {
            Text(title)
                .font(Vida.serif(21))
                .foregroundStyle(Vida.forest)
            content
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }
}

private struct BulletList: View {
    let items: [String]

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            ForEach(Array(items.enumerated()), id: \.offset) { _, item in
                HStack(alignment: .firstTextBaseline, spacing: 8) {
                    Text("•").foregroundStyle(Vida.moss).accessibilityHidden(true)
                    Text(item)
                        .foregroundStyle(Vida.ink)
                        .fixedSize(horizontal: false, vertical: true)
                }
                .font(Vida.sans(15))
                .lineSpacing(4)
            }
        }
    }
}

private struct Pill: View {
    let text: String
    var strong = false

    var body: some View {
        Text(text)
            .font(Vida.sans(11, weight: .semibold))
            .foregroundStyle(strong ? Vida.cream : Vida.forest)
            .padding(.horizontal, 9)
            .padding(.vertical, 4)
            .background(strong ? Vida.moss : Vida.sage.opacity(0.22), in: Capsule())
    }
}

private struct Paragraph: View {
    let text: String

    var body: some View {
        Text(text)
            .font(Vida.sans(15))
            .foregroundStyle(Vida.ink)
            .lineSpacing(5)
            .fixedSize(horizontal: false, vertical: true)
    }
}

struct BodyWeatherResultView: View {
    let result: BodyWeatherResult

    var body: some View {
        VStack(alignment: .leading, spacing: 24) {
            Text(result.summary)
                .font(Vida.serif(22))
                .foregroundStyle(Vida.forest)
                .fixedSize(horizontal: false, vertical: true)

            VStack(spacing: 10) {
                ForEach(result.forecast) { day in
                    VStack(alignment: .leading, spacing: 8) {
                        HStack {
                            Text(day.day)
                                .font(Vida.sans(15, weight: .semibold))
                                .foregroundStyle(Vida.forest)
                            Spacer()
                            Pill(text: "Energy \(day.energy)")
                            Pill(text: "\(day.riskLevel.capitalized) risk", strong: day.riskLevel == "elevated" || day.riskLevel == "high")
                        }
                        Text(day.headline)
                            .font(Vida.sans(15, weight: .medium))
                            .foregroundStyle(Vida.ink)
                            .fixedSize(horizontal: false, vertical: true)
                        Text(day.why)
                            .font(Vida.sans(13))
                            .foregroundStyle(Vida.inkSoft)
                            .lineSpacing(3)
                            .fixedSize(horizontal: false, vertical: true)
                        if !day.actions.isEmpty {
                            Text("Try: " + day.actions.joined(separator: " · "))
                                .font(Vida.sans(13, weight: .medium))
                                .foregroundStyle(Vida.moss)
                                .lineSpacing(3)
                                .fixedSize(horizontal: false, vertical: true)
                        }
                    }
                    .paperCard(padding: 16)
                    .accessibilityElement(children: .combine)
                }
            }

            if !result.patterns.isEmpty {
                InsightSection(title: "Patterns Vida noticed") { BulletList(items: result.patterns) }
            }
            if !result.topTriggers.isEmpty {
                InsightSection(title: "What tends to drive them") { BulletList(items: result.topTriggers) }
            }
            if !result.weeklyActions.isEmpty {
                InsightSection(title: "This week, focus on") { BulletList(items: result.weeklyActions) }
            }
            if !result.disclaimer.isEmpty {
                Text(result.disclaimer).font(Vida.sans(12)).foregroundStyle(Vida.taupe)
            }
        }
    }
}

struct DifferentialResultView: View {
    let result: DifferentialResult

    var body: some View {
        VStack(alignment: .leading, spacing: 24) {
            Text(result.summary)
                .font(Vida.serif(22))
                .foregroundStyle(Vida.forest)
                .fixedSize(horizontal: false, vertical: true)

            if !result.patterns.isEmpty {
                InsightSection(title: "Patterns in your tracking") { BulletList(items: result.patterns) }
            }

            if result.differentials.isEmpty {
                Paragraph(text: "Your patterns don't point clearly anywhere yet. The next steps below say what to track so the picture gets clearer.")
            } else {
                InsightSection(title: "Worth exploring with a doctor") {
                    VStack(spacing: 10) {
                        ForEach(result.differentials) { candidate in
                            VStack(alignment: .leading, spacing: 10) {
                                HStack(alignment: .firstTextBaseline) {
                                    Text(candidate.condition)
                                        .font(Vida.sans(16, weight: .semibold))
                                        .foregroundStyle(Vida.forest)
                                        .fixedSize(horizontal: false, vertical: true)
                                    Spacer(minLength: 8)
                                    Pill(text: "\(candidate.matchStrength.capitalized) fit", strong: candidate.matchStrength == "high")
                                }
                                Text(candidate.why)
                                    .font(Vida.sans(14))
                                    .foregroundStyle(Vida.ink)
                                    .lineSpacing(4)
                                    .fixedSize(horizontal: false, vertical: true)
                                labeled("Tests to ask about", candidate.testsToConsider)
                                labeled("Who evaluates it", candidate.specialists)
                                labeled("Get seen promptly for", candidate.redFlags)
                            }
                            .paperCard(padding: 16)
                        }
                    }
                }
            }

            if !result.advocacyNotes.isEmpty {
                InsightSection(title: "If you're dismissed") { BulletList(items: result.advocacyNotes) }
            }
            if !result.nextSteps.isEmpty {
                InsightSection(title: "Next steps") { BulletList(items: result.nextSteps) }
            }
            if !result.disclaimer.isEmpty {
                Text(result.disclaimer).font(Vida.sans(12)).foregroundStyle(Vida.taupe)
            }
        }
    }

    @ViewBuilder
    private func labeled(_ title: String, _ items: [String]) -> some View {
        if !items.isEmpty {
            VStack(alignment: .leading, spacing: 4) {
                Eyebrow(text: title)
                Text(items.joined(separator: " · "))
                    .font(Vida.sans(13))
                    .foregroundStyle(Vida.inkSoft)
                    .lineSpacing(3)
                    .fixedSize(horizontal: false, vertical: true)
            }
        }
    }
}

struct ConciergeResultView: View {
    let result: ConciergeResult

    var body: some View {
        VStack(alignment: .leading, spacing: 24) {
            Paragraph(text: result.visitSummary)

            InsightSection(title: "Your story, to read aloud") {
                Text(result.symptomNarrative)
                    .font(Vida.serif(17))
                    .foregroundStyle(Vida.forest)
                    .lineSpacing(5)
                    .fixedSize(horizontal: false, vertical: true)
                    .padding(16)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .background(Vida.sage.opacity(0.14), in: RoundedRectangle(cornerRadius: 16, style: .continuous))
                    .textSelection(.enabled)
            }

            if !result.keyMetrics.isEmpty {
                InsightSection(title: "Numbers to share") {
                    VStack(spacing: 8) {
                        ForEach(result.keyMetrics) { metric in
                            VStack(alignment: .leading, spacing: 3) {
                                HStack(alignment: .firstTextBaseline) {
                                    Text(metric.label)
                                        .font(Vida.sans(14, weight: .semibold))
                                        .foregroundStyle(Vida.forest)
                                    Spacer(minLength: 8)
                                    Text(metric.value)
                                        .font(Vida.sans(14))
                                        .foregroundStyle(Vida.ink)
                                        .multilineTextAlignment(.trailing)
                                }
                                if !metric.context.isEmpty {
                                    Text(metric.context)
                                        .font(Vida.sans(12))
                                        .foregroundStyle(Vida.inkSoft)
                                        .fixedSize(horizontal: false, vertical: true)
                                }
                            }
                            .paperCard(padding: 14)
                            .accessibilityElement(children: .combine)
                        }
                    }
                }
            }
            if !result.questionsToAsk.isEmpty {
                InsightSection(title: "Questions to ask") { BulletList(items: result.questionsToAsk) }
            }
            if !result.testsToRequest.isEmpty {
                InsightSection(title: "Tests worth asking about") { BulletList(items: result.testsToRequest) }
            }
            if !result.advocacyScript.isEmpty {
                InsightSection(title: "If you feel dismissed, say") {
                    Paragraph(text: result.advocacyScript).textSelection(.enabled)
                }
            }
            if !result.whatToBring.isEmpty {
                InsightSection(title: "What to bring") { BulletList(items: result.whatToBring) }
            }
            if !result.disclaimer.isEmpty {
                Text(result.disclaimer).font(Vida.sans(12)).foregroundStyle(Vida.taupe)
            }
        }
    }
}
